### ISSUE TITLE
Link error on Mac OS X 10.11.4 

### ISSUE THREAD

**Issue by jedwards4b** [jmrosinski/GPTL#4] opened 2016-04-19 19:22 UTC
Any ideas?  
ld: in /Users/jedwards/cesm/scratch/sharedlibroot.20160419_183857/gnu/mpich/nodebug/nothreads/lib/libgptl.a(gptl.o), in section __TEXT,__text reloc 100: length != 2 and X86_64_RELOC_GOT not supported for architecture x86_64

**Comment by jmrosinski** [comment] 2016-04-20 01:43
No ideas at all, particularly without info about what gcc and gfortran you
are using, or macros.make contents.

The latest rev on github just built fine on my Mac OS 10.10.5 machine, with
the committed macros.make.macos.  gcc and gfortran are the following:

% gcc --version
Apple LLVM version 7.0.0 (clang-700.0.72)

% gfortran --version
GNU Fortran (Homebrew gcc 5.2.0) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.

Jim Rosinski

**Comment by jedwards4b** [comment] 2016-04-20 01:52
Sorry Jim - here are the compiler details, but I just realised that this
particular code is using a rather old and locally modified version of
gptl.  I'll try again with a fresh version.

elm:~ jedwards$ gcc --version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr
--with-gxx-include-dir=/usr/include/c++/4.2.1

Apple LLVM version 7.3.0 (clang-703.0.29)

Target: x86_64-apple-darwin15.4.0

Thread model: posix

InstalledDir:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

elm:~ jedwards$ gfortran --version

GNU Fortran (GCC) 5.2.0

Copyright (C) 2015 Free Software Foundation, Inc.

On Tue, Apr 19, 2016 at 7:43 PM, Jim Rosinski notifications@github.com
wrote:

> No ideas at all, particularly without info about what gcc and gfortran you
> are using, or macros.make contents.
> 
> The latest rev on github just built fine on my Mac OS 10.10.5 machine, with
> the committed macros.make.macos. gcc and gfortran are the following:
> 
> % gcc --version
> Apple LLVM version 7.0.0 (clang-700.0.72)
> 
> % gfortran --version
> GNU Fortran (Homebrew gcc 5.2.0) 5.2.0
> Copyright (C) 2015 Free Software Foundation, Inc.
> 
> Jim Rosinski
> 
> On Tue, Apr 19, 2016 at 1:22 PM, jedwards4b notifications@github.com
> wrote:
> 
> > Any ideas?
> > 
> > ld: in
> > 
> > /Users/jedwards/cesm/scratch/sharedlibroot.20160419_183857/gnu/mpich/nodebug/nothreads/lib/libgptl.a(gptl.o),
> > in section __TEXT,__text reloc 100: length != 2 and X86_64_RELOC_GOT not
> > supported for architecture x86_64
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/jmrosinski/GPTL/issues/4
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jmrosinski/GPTL/issues/4#issuecomment-212205908

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jedwards4b** [comment] 2016-04-27 15:15
Hi Jim,

It turns out that I still get this error on link with the latest GPTL.
 I've searched around on google and haven't found any clues yet on how to
fix it.

On Tue, Apr 19, 2016 at 7:51 PM, Jim Edwards jedwards@ucar.edu wrote:

> Sorry Jim - here are the compiler details, but I just realised that this
> particular code is using a rather old and locally modified version of
> gptl.  I'll try again with a fresh version.
> 
> elm:~ jedwards$ gcc --version
> 
> Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr
> --with-gxx-include-dir=/usr/include/c++/4.2.1
> 
> Apple LLVM version 7.3.0 (clang-703.0.29)
> 
> Target: x86_64-apple-darwin15.4.0
> 
> Thread model: posix
> 
> InstalledDir:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> 
> elm:~ jedwards$ gfortran --version
> 
> GNU Fortran (GCC) 5.2.0
> 
> Copyright (C) 2015 Free Software Foundation, Inc.
> 
> On Tue, Apr 19, 2016 at 7:43 PM, Jim Rosinski notifications@github.com
> wrote:
> 
> > No ideas at all, particularly without info about what gcc and gfortran you
> > are using, or macros.make contents.
> > 
> > The latest rev on github just built fine on my Mac OS 10.10.5 machine,
> > with
> > the committed macros.make.macos. gcc and gfortran are the following:
> > 
> > % gcc --version
> > Apple LLVM version 7.0.0 (clang-700.0.72)
> > 
> > % gfortran --version
> > GNU Fortran (Homebrew gcc 5.2.0) 5.2.0
> > Copyright (C) 2015 Free Software Foundation, Inc.
> > 
> > Jim Rosinski
> > 
> > On Tue, Apr 19, 2016 at 1:22 PM, jedwards4b notifications@github.com
> > wrote:
> > 
> > > Any ideas?
> > > 
> > > ld: in
> > > 
> > > /Users/jedwards/cesm/scratch/sharedlibroot.20160419_183857/gnu/mpich/nodebug/nothreads/lib/libgptl.a(gptl.o),
> > > in section __TEXT,__text reloc 100: length != 2 and X86_64_RELOC_GOT not
> > > supported for architecture x86_64
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jmrosinski/GPTL/issues/4
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/jmrosinski/GPTL/issues/4#issuecomment-212205908
> 
> ## 
> 
> Jim Edwards
> 
> CESM Software Engineer
> National Center for Atmospheric Research
> Boulder, CO

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jmrosinski** [comment] 2016-04-27 22:11
Are you using the vanilla GPTL source code, with no local modifications? If
so, can you send me your macros.make? Presumably you started with
macros.make.macos. I can have a look.

Jim

**Comment by jedwards4b** [comment] 2016-04-27 22:19
yes, using macros.make.macos  the error doesn't happen until i link the
executable.

On Wed, Apr 27, 2016 at 4:11 PM, Jim Rosinski notifications@github.com
wrote:

> Are you using the vanilla GPTL source code, with no local modifications? If
> so, can you send me your macros.make? Presumably you started with
> macros.make.macos. I can have a look.
> 
> Jim
> 
> On Wed, Apr 27, 2016 at 9:15 AM, jedwards4b notifications@github.com
> wrote:
> 
> > Hi Jim,
> > 
> > It turns out that I still get this error on link with the latest GPTL.
> > I've searched around on google and haven't found any clues yet on how to
> > fix it.
> > 
> > On Tue, Apr 19, 2016 at 7:51 PM, Jim Edwards jedwards@ucar.edu wrote:
> > 
> > > Sorry Jim - here are the compiler details, but I just realised that
> > > this
> > > particular code is using a rather old and locally modified version of
> > > gptl. I'll try again with a fresh version.
> > > 
> > > elm:~ jedwards$ gcc --version
> > > 
> > > Configured with:
> > > --prefix=/Applications/Xcode.app/Contents/Developer/usr
> > > --with-gxx-include-dir=/usr/include/c++/4.2.1
> > > 
> > > Apple LLVM version 7.3.0 (clang-703.0.29)
> > > 
> > > Target: x86_64-apple-darwin15.4.0
> > > 
> > > Thread model: posix
> > > 
> > > InstalledDir:
> > 
> > /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> > 
> > > elm:~ jedwards$ gfortran --version
> > > 
> > > GNU Fortran (GCC) 5.2.0
> > > 
> > > Copyright (C) 2015 Free Software Foundation, Inc.
> > > 
> > > On Tue, Apr 19, 2016 at 7:43 PM, Jim Rosinski <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > No ideas at all, particularly without info about what gcc and gfortran
> > > > you
> > > > are using, or macros.make contents.
> > > > 
> > > > The latest rev on github just built fine on my Mac OS 10.10.5 machine,
> > > > with
> > > > the committed macros.make.macos. gcc and gfortran are the following:
> > > > 
> > > > % gcc --version
> > > > Apple LLVM version 7.0.0 (clang-700.0.72)
> > > > 
> > > > % gfortran --version
> > > > GNU Fortran (Homebrew gcc 5.2.0) 5.2.0
> > > > Copyright (C) 2015 Free Software Foundation, Inc.
> > > > 
> > > > Jim Rosinski
> > > > 
> > > > On Tue, Apr 19, 2016 at 1:22 PM, jedwards4b <notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > Any ideas?
> > > > > 
> > > > > ld: in
> > 
> > /Users/jedwards/cesm/scratch/sharedlibroot.20160419_183857/gnu/mpich/nodebug/nothreads/lib/libgptl.a(gptl.o),
> > 
> > > > > in section __TEXT,__text reloc 100: length != 2 and X86_64_RELOC_GOT
> > > > > not
> > > > > supported for architecture x86_64
> > > > > 
> > > > > —
> > > > > You are receiving this because you are subscribed to this thread.
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/jmrosinski/GPTL/issues/4
> > > > 
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/jmrosinski/GPTL/issues/4#issuecomment-212205908
> > > 
> > > ## 
> > > 
> > > Jim Edwards
> > > 
> > > CESM Software Engineer
> > > National Center for Atmospheric Research
> > > Boulder, CO
> > 
> > ## 
> > 
> > Jim Edwards
> > 
> > CESM Software Engineer
> > National Center for Atmospheric Research
> > Boulder, CO
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/jmrosinski/GPTL/issues/4#issuecomment-215116264
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jmrosinski/GPTL/issues/4#issuecomment-215247184

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jmrosinski** [comment] 2016-04-29 15:30
Presumably you're talking about one of the GPTL test executables in either
ctests/ or ftests/ that gets built automatically as part of the GPTL "make"
procedure? If so, which one? If not and the GPTL build procedure linked all
these executables successfully, then the problem is likely in the
application rather than the GPTL library.

Jim

**Comment by edhartnett** [comment] 2018-11-01 21:24
Is this still an issue?

PIO should now switch to the newly release version 5.6.0 of the GPTL C library, and remove the internal GPTL code in PIO.

**Comment by edhartnett** [comment] 2019-04-18 13:31
PIO (in autotools build) now uses the externally installed GPTL library.  I will convert the cmake build similarly. The I will remove PIO's version of GPTL code. This issue can be closed.

**Comment by jmrosinski** [comment] 2020-07-02 00:07
If this is still an issue please re-open. MacOS build was working as of latest release.

**Closed as completed by jmrosinski** 2020-07-02 00:07 UTC
